language: python
python:
  - "3.5.2"

install:
  - pip install  -r requirements.txt
  - pip install coveralls

script:
  - pytest
  - pytest --with-coverage --cover-package=Api
  
after_success : 
  - coveralls
