language: python
python:
  - "3.5.2"

install:
  - pip install  -r requirements.txt
  - pip install coveralls
  
script: 
  - source .travis.sh
  - pytest --cov=Api test/

after_success : 
  - coveralls
